name: Cron.Weekly
on:
  schedule:
    - cron: 0 12 * * 0
  repository_dispatch:
  workflow_dispatch:

jobs:
  exec:
    name: Update games list on ubuntu-latest with Python 3.x
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Run pip3
      run: pip3 install -r requirements.txt
    - name: Execute Script
      run: python3 gamesListUpdater.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
    - name: Commit Changes
      uses: EndBug/add-and-commit@v4
      with:
        message: 'Updated the games list'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
